<!DOCTYPE html>
<html>
<head>
	<title>Login form</title>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #afacac;
		}
		.container {
			background-color: rgb(255, 255, 255);
			padding: 20px;
			max-width: 400px;
			margin: 0 auto;
			border-radius: 5px;
			box-shadow: 0px 2px 5px rgba(83, 79, 79, 0.3);
            box-shadow: 10px 10px 5px rgb(213, 243, 81);
		}
		h2 {
			text-align: center;
            font-size: 40px;
           font-style: oblique;
			color: rgb(12, 12, 12);
			margin-bottom: 30px;
		}
		input[type="text"],
		input[type="password"] {
			width: 100%;
			padding: 12px 20px;
			margin: 8px 0;
			box-sizing: border-box;
			border: 2px solid rgb(134, 90, 90);
			border-radius: 4px;
			font-size: 16px;
           
		}
		input[type="submit"] {
			background-color: #4CAF50;
			color: #fff;
			padding: 12px 20px;
			margin-top: 20px;
			border: none;
			border-radius: 4px;
			cursor: pointer;
			font-size: 16px;
		}
		input[type="submit"]:hover {
			background-color: #8fe48f;
        }
        label[for="username"],
        [for="password"]{
            font-weight: bold;
        }

        
	</style>
</head>
<body>
	<div class="container">
		<h2>Login</h2>
		<form>
			<label for="username">Username:</label>
			<input type="text" id="username" name="username" placeholder="Enter your username">
			<label for="password">Password:</label>
			<input type="password" id="password" name="password" placeholder="Enter your password">
			<input type="submit" value="Login">
		</form>
	</div>
</body>
</html>
